### ISSUE TITLE
Advice on formatting html tables

### ISSUE THREAD

**Issue by jdebacker** [compute-tooling/compute-studio-kit#9]
I'm not super pleased with how the CCC output table is rendering.  See example [here](https://www.compute.studio/PSLmodels/Cost-of-Capital-Calculator/20/).  

The [`summary_table` function that is used ](https://github.com/PSLmodels/Cost-of-Capital-Calculator/blob/b478377c06aa94f3cf033a2664f8e93329957593/ccc/calculator.py#L266) puts spaces before names of the subgroups (e.g.,  the result for all corporate investment has the string 'Corporations', , but the results for equity finance investments by corporates, which is on the next row of the table, should be indented three spaces.  This done in the string to be used to label that row: '   Equity Financed' -- see [this line](https://github.com/PSLmodels/Cost-of-Capital-Calculator/blob/b478377c06aa94f3cf033a2664f8e93329957593/ccc/calculator.py#L330)).  But in the html table, all these strings are right up against the left column.  In addition, I'd like the leftmost column with strings to be left aligned, but the other column with numbers to be centered under the column titles.  

This is not a CS issue per se, but I'd like to hear feedback from CS users about how I can better format this table.

cc @hdoupe @Peter-Metz

Here's the HTML for generating the table:
<body>
<style  type="text/css" >\n    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col0 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col1 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col2 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }    #T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col3 {\n            font-size:  12pt;\n            font-family:  Calibri;\n            text-align:  left;\n        }</style><table id="T_9da0dede_0626_11ea_8d1b_9801a7af4499" ><thead>    <tr>        <th class="col_heading level0 col0" ></th>        <th class="col_heading level0 col1" >Marginal Effective Total Tax Rate Under Baseline Policy</th>        <th class="col_heading level0 col2" >Marginal Effective Total Tax Rate Under Reform Policy</th>        <th class="col_heading level0 col3" >Change from Baseline (pp)</th>    </tr></thead><tbody>\n                <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col0" class="data row0 col0" >Overall</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col1" class="data row0 col1" >18.36</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col2" class="data row0 col2" >26.02</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row0_col3" class="data row0 col3" >7.65</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col0" class="data row1 col0" >Corporations</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col1" class="data row1 col1" >19</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col2" class="data row1 col2" >29.25</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row1_col3" class="data row1 col3" >10.25</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col0" class="data row2 col0" >   Equity Financed</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col1" class="data row2 col1" >21.94</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col2" class="data row2 col2" >35.91</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row2_col3" class="data row2 col3" >13.97</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col0" class="data row3 col0" >   Debt Financed</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col1" class="data row3 col1" >7.02</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col2" class="data row3 col2" >-8.51</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row3_col3" class="data row3 col3" >-15.53</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col0" class="data row4 col0" >Pass-Through Entities</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col1" class="data row4 col1" >19</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col2" class="data row4 col2" >23.09</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row4_col3" class="data row4 col3" >4.09</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col0" class="data row5 col0" >   Equity Financed</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col1" class="data row5 col1" >17.13</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col2" class="data row5 col2" >23.07</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row5_col3" class="data row5 col3" >5.94</td>\n            </tr>\n            <tr>\n                                <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col0" class="data row6 col0" >   Debt Financed</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col1" class="data row6 col1" >26.82</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col2" class="data row6 col2" >23.42</td>\n                        <td id="T_9da0dede_0626_11ea_8d1b_9801a7af4499row6_col3" class="data row6 col3" >-3.4</td>\n            </tr>\n    </tbody></table>
</body>

**Comment by hdoupe** [comment]
@Peter-Metz creates the HTML tables with code like this:

```python
# basic is a dataframe
table_basic = basic.to_html(
    classes="table table-striped table-hover"
)
```

https://github.com/PSLmodels/Tax-Cruncher/blob/024383ca7004f9bef96a179aba7a76881bfa23da/cs-config/cs_config/functions.py#L185-L187

The `classes` argument targets the bootstrap classes: table, table-striped, and table-hover. Including these bootstrap classes with your tables should go a long way towards making them look clean. But, you can customize them further by adding more classes. Bootstrap's [tables page](https://getbootstrap.com/docs/4.0/content/tables/) shows all of the different options for how to style HTML tables.

Does this make sense @jdebacker? If this information is helpful, I'll add it to the outputs docs so that publishers start with clean looking tables by default.

**Comment by Peter-Metz** [comment]
+1 on using bootstrap classes. The only thing I'll add is that you might try using a couple of `&nbsp;` (one space) instead of putting spaces in front of row titles to get the indent to render.

If that doesn't work, you could try adding a css class that adds some padding to certain row titles.

**Comment by jdebacker** [comment]
This is helpful!  Thanks @hdoupe and @Peter-Metz !
